"""Initial database schema

Revision ID: f45fb29a99ea
Revises: 
Create Date: 2026-08-22 16:29:24.460641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45fb29a99ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('appearance', sa.SmallInteger(), nullable=False),
    sa.Column('pulse', sa.SmallInteger(), nullable=False),
    sa.Column('grimace', sa.SmallInteger(), nullable=False),
    sa.Column('activity', sa.SmallInteger(), nullable=False),
    sa.Column('respiration', sa.SmallInteger(), nullable=False),
    sa.Column('apgar_total', sa.SmallInteger(), nullable=False),
    sa.Column('birth_week', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('birth_weight_input', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('birth_weight_unit', sa.String(length=8), nullable=False),
    sa.Column('birth_weight_g', sa.Integer(), nullable=False),
    sa.Column('maternal_age', sa.SmallInteger(), nullable=False),
    sa.Column('child_gender', sa.String(length=20), nullable=False),
    sa.Column('delivery_type', sa.String(length=30), nullable=False),
    sa.Column('delivery_complication', sa.Boolean(), nullable=False),
    sa.Column('family_history_status', sa.String(length=20), nullable=False),
    sa.Column('family_disease_name', sa.String(length=120), nullable=True),
    sa.Column('family_affected_relative', sa.String(length=30), nullable=True),
    sa.Column('raw_inputs', sa.JSON(), nullable=False),
    sa.Column('immediate_risk_index', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('immediate_risk_level', sa.String(length=20), nullable=False),
    sa.Column('birth_related_risk_index', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('birth_related_risk_level', sa.String(length=20), nullable=False),
    sa.Column('family_history_risk_index', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('family_history_risk_level', sa.String(length=20), nullable=False),
    sa.Column('overall_risk_index', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('confidence_reasons', sa.JSON(), nullable=False),
    sa.Column('main_contributing_factors', sa.JSON(), nullable=False),
    sa.Column('lower_impact_factors', sa.JSON(), nullable=False),
    sa.Column('triggered_rules', sa.JSON(), nullable=False),
    sa.Column('user_guidance', sa.JSON(), nullable=False),
    sa.Column('apgar_breakdown', sa.Text(), nullable=False),
    sa.Column('apgar_category', sa.String(length=40), nullable=False),
    sa.Column('apgar_severity', sa.String(length=20), nullable=False),
    sa.Column('apgar_component_detail', sa.JSON(), nullable=False),
    sa.Column('family_history_summary', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('result_snapshot', sa.JSON(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('activity BETWEEN 0 AND 2', name='ck_assess_activity'),
    sa.CheckConstraint('apgar_total BETWEEN 0 AND 10', name='ck_assess_apgar_total'),
    sa.CheckConstraint('appearance BETWEEN 0 AND 2', name='ck_assess_appearance'),
    sa.CheckConstraint('birth_weight_g > 0', name='ck_assess_birth_weight'),
    sa.CheckConstraint('grimace BETWEEN 0 AND 2', name='ck_assess_grimace'),
    sa.CheckConstraint('pulse BETWEEN 0 AND 2', name='ck_assess_pulse'),
    sa.CheckConstraint('respiration BETWEEN 0 AND 2', name='ck_assess_respiration'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_algorithm_version'), ['algorithm_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_overall_risk_index'), ['overall_risk_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_user_id'))
        batch_op.drop_index(batch_op.f('ix_assessments_risk_level'))
        batch_op.drop_index(batch_op.f('ix_assessments_overall_risk_index'))
        batch_op.drop_index(batch_op.f('ix_assessments_created_at'))
        batch_op.drop_index(batch_op.f('ix_assessments_algorithm_version'))

    op.drop_table('assessments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
